package it.unipv.ingsw.syzygy.excamp.modelDomain.lista;

public enum Camp {
	ARRAMPICATA,
	BASKET,
	CALCIO_LEEDS_UNITED,
	CINEMA,DEEJAY,
	EQUITAZIONE,
	GINNASTICA_ARTISTICA_VANESSA_FERRARI,
	INTERNAZIONALE_DI_FIORETTO,
	MOUNTAIN_BIKE,
	MULTISPORT_PLUS,
	MUSICAL,
	NUOTO,
	PARKOUR,
	RUGBY,
	STAGE_DANZA,
	STAGE_TEATRO_OSCAR,
	TENNIS_ALTA_QUALIFICAZIONE_PLUS,
	TRIATHLON,
	UYBA_VOLLEY_ACADEMY,
	VELA,
	WILD_NATURE
}
